name: Base64 Docker Build and Push
on:
  push:
    branches:
      - master

jobs:
  golang-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: list of files
        run: ls -la

      - name: Check go version
        run: go version

  golang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Test
        run: go test -v ./...
