name: Base64 Docker Build and Push
on:
  push:
    branches:
      - master

jobs:
  golang-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: list of files
        run: ls -la

      - name: Check go version
        run: go version

  golang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Test
        run: go test -v ./...

  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: titan29/base64-go:${{ github.run_number }}

      - name: Check docker images
        run: docker image ls